use_frameworks!

target 'ModuleManager_Example' do
  pod 'ModuleManager', :path => '../'

  target 'ModuleManager_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
